### PR TITLE
fix(toonily): update search path and selector

### PR DESCRIPTION
**Pull request by KaBankz**
Checklist:
- [x] Updated source's version for individual source changes
- [x] Updated all sources' versions for template changes
- [ ] Set appropriate `nsfw` value
- [x] Did not change `id` even if a source's name or language were changed
- [x] Tested the modifications by running it on the simulator or a test device

### CODE REVIEW

**Review by Skittyblock — CHANGES_REQUESTED** [review]
search is happening in "family mode" and I'm guessing that's probably not ideal. I think "&adult" needs to be appended to the search url.

**Comment by KaBankz** [comment]
> search is happening in "family mode" and I'm guessing that's probably not ideal. I think "&adult" needs to be appended to the search url.

Turns out toonily has a custom cookie (`toonily-mature=1`) that needs to be passed in for nsfw results to appear, it does not abide by the default `wpmanga-adault=1` cookie.

So, I updated the madara template to allow for passing in custom search cookies, and toonily search is working fine now...

Except, searching in toonily causes an infinite loop, and search results are duplicated infinitely, then the app crashes. The pagination for search requests is borked and even if there is only one page of results, it thinks there are more pages of results and requests them until the app crashes.

I tried looking around as to why this is happening, but I had no luck thus far.

**Comment by Skittyblock** [comment]
Looks like toonily formats the search url a bit differently. Madara template defines it as `/search/{page}/?s={string}&...`, but toonily's is like `/search/{string}/page/{page}/?...`. However, it appears like it works the same if you use the s URL param still and just replace the path component with any string, so like `/search/x/page/{page}/?s={string}&...` works I think.

The template should probably be changed to allow for this, but I'm not sure if it's something unique to toonily or if other madara sources do this as well.

**Comment by KaBankz** [comment]
You were right, the search url was messed up, I fixed toonily's search path but toonily search broke if `&post_type=wp-manga` was set. So I updated the template and helper to make `post_type` an overrideable variable, and everything works as intended now.

**Review by Skittyblock — COMMENTED** [review]
Only Toonily version should be bumped since the functionality of the other sources has stayed the same. Otherwise looks good.

**Comment by KaBankz** [comment]
> Only Toonily version should be bumped since the functionality of the other sources has stayed the same. Otherwise looks good.

Oh, I thought you're supposed to update all source versions for template updates.

No big deal tho, I'll revert that commit real quick

**Comment by Skittyblock** [comment]
Typically yeah, but there's no reason to push updates out to everyone when nothing in the source was changed.

**Pull request merged**
