### PR TITLE
chore: remove dead sources, format & lint everything 

### PR DESCRIPTION
**Pull request by KaBankz**
Removed Sources:
- Twilight Scans
- MangaZuki
- Koushoku

### CODE REVIEW

**Comment by Skittyblock** [comment]
pulling main should fix build errors

**Comment by KaBankz** [comment]
I just let clippy auto fix all lint errors that it could find

**Comment by Skittyblock** [comment]
looks like DynastyScans icon needs fixing

**Comment by Skittyblock** [comment]
pulling main should fix dynasty icon

**Pull request merged**
