### PR TITLE
Update ComicOnlineFree URL

### LINKED ISSUE #478: ComicOnlineFree URL changed. needs update
all my library entries using the source don't work anymore and every chapter i've downloaded have disappeared despite still being there

from [comiconlinefree.net](url) to [comiconlinefree.org](url)

### PR DESCRIPTION
**Pull request by pandeynmn**
Checklist:
- [ ] Updated source's version for individual source changes
- [ ] Updated all sources' versions for template changes
- [ ] Set appropriate `nsfw` value
- [ ] Did not change `id` even if a source's name or language were changed
- [ ] Tested the modifications by running it on the simulator or a test device 

fixes #478

### CODE REVIEW

**Comment by pandeynmn** [comment]
Ready to merge

**Comment by pandeynmn** [comment]
I also updated the gitignore to add all target folders to ignore as some new target files were not being ignored in wp-comics

**Review by Skittyblock — CHANGES_REQUESTED** [review]
you also need to update the URL in the actual source code

**Comment by medievalegg** [comment]
I hope this was the correct place to comment but this source no longer works at least under the url it currently uses.

**Pull request closed without merging**
